name: Build and deploy manual

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  builddocs:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Edit PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --user --upgrade -r doc/requirements.txt

      - name: Check some stuff about Python
        run: |
          which python
          which python3

      - name: Build the docs
        working-directory: doc
        run: |
          make

      - name: Move built HTML docs
        if: github.ref == 'refs/heads/main'
        working-directory: doc
        run: |
          mv _build/html ../docs_output

      - name: Upload artifacts
        # if: github.ref == 'refs/heads/main'
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v1
        with:
          name: docs_output
          path: docs_output/

  deploy:
    name: deploy
    needs: builddocs
    # if: github.ref == 'refs/heads/main'
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: docs_output # optional
          # Destination path
          path: docs_output # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS }} 
        with:
          build_dir: docs_output/
